//@version=6
strategy("v6 Functions - strategy E2E", overlay = true, default_qty_value=10.0)

int   lenInput = input.int(14, "Length")
float ma       = ta.sma(close, lenInput)
bool  goLong   = ta.crossover(close, ma)
bool  goShort  = ta.crossunder(close, ma)

if goLong
    strategy.entry("Long", strategy.long)

if goShort
    strategy.entry("Short", strategy.short)
    strategy.close("Long")

strategy.exit("Long Exit", from_entry="Long", stop=low[1], limit=high[1])
strategy.order("ManualLong", strategy.long, qty=1.0)
strategy.cancel("ManualLong")

strategy.risk.max_drawdown(10.0, strategy.percent_of_equity)
strategy.risk.max_cons_loss_days(3)

float equity  = strategy.equity
float pnl     = strategy.netprofit
int   openpos = strategy.opentrades
bool  inPos   = strategy.position_size != 0.0

plot(ma, title="MA")
plotshape(goLong, style=shape.arrowup, location=location.belowbar, color=color.green)
plotshape(goShort, style=shape.arrowdown, location=location.abovebar, color=color.red)
